name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: setup-android
      - uses: msfjarvis/setup-android@0.2
        with:
          entrypoint: ./gradlew
          args: dependencies spotlessApply detekt assembleDebug
